// Question
export const REQUEST_RANDOM_QUESTION = 'REQUEST_RANDOM_QUESTION';
export const RECEIVE_RANDOM_QUESTION = 'RECEIVE_RANDOM_QUESTION';
export const SHOW_OR_HIDE_ADD_QUESTION = 'SHOW_OR_HIDE_ADD_QUESTION';

// UI related
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const QUESTION_POSTED = 'QUESTION_POSTED';
export const QUESTION_CREATED = 'QUESTION_CREATED';
export const CLEAR_UI_STATE = 'CLEAR_UI_STATE';

// User
export const CHECK_FOR_USER = 'CHECK_FOR_USER';
export const STORE_USER = 'STORE_USER';
