// Question
export const REQUEST_RANDOM_QUESTION = 'REQUEST_RANDOM_QUESTION';
export const RECEIVE_RANDOM_QUESTION = 'RECEIVE_RANDOM_QUESTION';
export const SHOW_OR_HIDE_ADD_QUESTION = 'SHOW_OR_HIDE_ADD_QUESTION';
export const CREATE_QUESTION = 'CREATE_QUESTION';

// User
export const CHECK_FOR_USER = 'CHECK_FOR_USER';
export const STORE_USER = 'STORE_USER';
